project_id = "nttvbhtcubceobwqehut"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-email-infra]
    verify_jwt = false
  [functions.fetch-currency-rates]
    verify_jwt = false
  [functions.generate-itinerary]
    verify_jwt = false
  [functions.get-public-quote]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.scrape-package]
    verify_jwt = false
