-- Migration: Add specific columns to file_services for detailed metadata of flights, lodgings, cruises, transfers, insurance, and rental cars.
ALTER TABLE public.file_services 
  ADD COLUMN IF NOT EXISTS end_date DATE,
  ADD COLUMN IF NOT EXISTS origin TEXT,
  ADD COLUMN IF NOT EXISTS destination TEXT,
  ADD COLUMN IF NOT EXISTS airline TEXT,
  ADD COLUMN IF NOT EXISTS flight_number TEXT,
  ADD COLUMN IF NOT EXISTS cabin_class TEXT,
  ADD COLUMN IF NOT EXISTS regime TEXT,
  ADD COLUMN IF NOT EXISTS room_type TEXT,
  ADD COLUMN IF NOT EXISTS pickup_location TEXT,
  ADD COLUMN IF NOT EXISTS dropoff_location TEXT,
  ADD COLUMN IF NOT EXISTS company TEXT,
  ADD COLUMN IF NOT EXISTS departure_time TEXT,
  ADD COLUMN IF NOT EXISTS arrival_time TEXT,
  ADD COLUMN IF NOT EXISTS luggage TEXT,
  ADD COLUMN IF NOT EXISTS luggage_type TEXT,
  ADD COLUMN IF NOT EXISTS hotel_category TEXT,
  ADD COLUMN IF NOT EXISTS ship_name TEXT,
  ADD COLUMN IF NOT EXISTS embarkation_port TEXT,
  ADD COLUMN IF NOT EXISTS disembarkation_port TEXT,
  ADD COLUMN IF NOT EXISTS deck TEXT,
  ADD COLUMN IF NOT EXISTS cabin_number TEXT,
  ADD COLUMN IF NOT EXISTS coverage TEXT,
  ADD COLUMN IF NOT EXISTS insurance_plan TEXT;
