// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const customFetch = async (url: RequestInfo | URL, options?: RequestInit) => {
  const response = await fetch(url, options);
  if (options?.method && ['POST', 'PATCH', 'DELETE'].includes(options.method)) {
    const urlStr = url instanceof Request ? url.url : url.toString();
    // Only dispatch on actual PostgREST table CRUD operations.
    // We exclude /auth/v1/, /functions/v1/, and /rpc/ to prevent infinite loops
    // where a read operation (like an Edge Function or RPC) triggers a global refresh.
    if (urlStr.includes('/rest/v1/') && !urlStr.includes('/rest/v1/rpc/')) {
      if (response.ok && typeof window !== 'undefined') {
        window.dispatchEvent(new CustomEvent('global-crud-success'));
      }
    }
  }
  return response;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: customFetch,
  }
});